### ISSUE TITLE
Upgraders Broken by the Recent Changes

### ISSUE THREAD

**Issue by torin555** [cyberblast/screeps.behaviour-action-pattern#106]
Upgraders seem to have been broken by one of the recent modifications to the upgrader behavior file. (Sometime after version 296de6f because reverting to that version of the file fixes them.) With the newer changes, the Upgrader will just sit on a full container 3 squares from the controller and not take any energy from it. I can narrow down which commit caused the issue better if I have some free time tomorrow, but for now, I figured I'd mention it.

**Comment by cyberblast** [comment]
confirmed. (omg)
Should run better now

**Comment by torin555** [comment]
Appears solved :)
