### ISSUE TITLE
Containers are not being repaired

### ISSUE THREAD

**Issue by SirLovi** [cyberblast/screeps.behaviour-action-pattern#107]

**Comment by cyberblast** [comment]
Thats strange. are you sure?
They should get repaired when below a certain limit, regarding to rcl...

**Comment by SirLovi** [comment]
I thought they are but all of my oldest containers decayed to zero and started a chain of errors.
I immediately started building them again manually but this shouldn't be the case.
Maybe they are not counted as ''repairableSites''

**Comment by cyberblast** [comment]
I can't confirm that. looking in my own rooms they get repaired constantly... :/ 
strange

**Comment by SirLovi** [comment]
I figured out the problem.. The towers weren't able to keep up with the number of decayables.. It should fix itself in time
