### ISSUE TITLE
o.store undefined

### ISSUE THREAD

**Issue by torin555** [cyberblast/screeps.behaviour-action-pattern#119]
```
creep.action.uncharging:17
            let e = o.store.energy / (count ? count+1 : 1);
                           ^
TypeError: Cannot read property 'energy' of undefined
    at o (creep.action.uncharging:17:28)
    at arrayEach (/opt/engine/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/opt/engine/node_modules/lodash/index.js:3345:13)
    at action.newTarget (creep.action.uncharging:23:11)
    at assign (creep.Action:122:50)
    at Object.module.exports.nextAction (creep.behaviour.worker:84:24)
    at Object.module.exports.run (creep.behaviour.worker:7:18)
    at Creep.run (creep:60:43)
    at creep (creep:52:38)
```

This happens in version 912da61 and later. Happens when a worker is going trying to get energy from a container. Reverting the file to f9c3f28 seems to fix the issue.

**Comment by torin555** [comment]
The circumstances are apparently very specific, because after waiting for a few minutes and changing the file back to my newest version I don't get the error.

**Comment by torin555** [comment]
The error also happens with Haulers, (makes sense because they use that code too). Reverting doesn't fix that obviously because the "fix" is basically to stop using that piece of code for workers lol. Still not sure what actually causes it to be undefined though.

**Comment by cyberblast** [comment]
Hi torin. 
are you using links? 
In room.js line 321+ change to 
`filter: (structure) => ( structure.structureType == STRUCTURE_CONTAINER )` 
Links are not utilized yet, have no store but are included in chargeables. So may also be in chargeablesIn when near source. I create a fix for this... 
But can you check if this is the solution for problem? Could still be something else...

**Comment by torin555** [comment]
Ah I think it was caused by having a link. Makes sense

**Comment by cyberblast** [comment]
Please just close it, when you think its gone ;)

**Comment by torin555** [comment]
Can't test links atm but for now We'll just close this assuming its fixed.
