### ISSUE TITLE
Invading: Target Towers

### ISSUE THREAD

**Issue by cyberblast** [cyberblast/screeps.behaviour-action-pattern#18]
towers should be preferred targets.  
They could maybe be priorized after creeps with HEAL, ATTACK or ATTACK_RANGED parts and before other hostile creeps.  

Interested in supporting the project? ;)

**Comment by SirLovi** [comment]
Was looking for inspiration in the other's codes. No one prioritises Towers..

Have you tried using the Destroy flag on the tower? 
From my current experience invasions to tower defended rooms are a bloodbath, so I'm not attempting again..

**Comment by cyberblast** [comment]
No, I don't have a certain case actually. Destroy Flags would certainly do, but towers are quite common and should be taken into consideration. And as they are one of the bigger threat, they should have a good priority.  
Thought this would be an interesting one, as it should be quite simple to extend the current priorization and it is a hole in a topic which is almost complete, not a completely new one. 
I will take care of it...

**Comment by cyberblast** [comment]
To validate: 
* Invasion is working
* Prio order is respected
