### ISSUE TITLE
Corrupt creep spawning

### ISSUE THREAD

**Issue by SirLovi** [cyberblast/screeps.behaviour-action-pattern#27]
Code currently doesn't find any workers in a room so it doesn't spawn anything.

creep:154
            var population = this.globalMeasurement ? Game.population[this.type] : room.population[this.type];
___________________________________________________________________________________________^
TypeError: Cannot read property 'worker' of undefined
    at isValidSetup (creep:154:99)
    at Array.forEach (native)
    at Object.mod.createCreep (spawn:16:11)
    at Object.mod.loop (spawn:7:22)
    at Object.module.exports.loop (main:8:23)
    at __mainLoop:1:52

**Comment by SirLovi** [comment]
Maybe solved by using:
`spawn.room.population[this.type];`
Instead of
`room.population[this.type];`

**Comment by SirLovi** [comment]
After spawning starting workers the code starts to work perfectly again.
The problems occurs only when population is completely wiped out.
Could be fixed by using something like _undefined checking_ to automatically spawn new creeps when no creep is alive.

**Comment by cyberblast** [comment]
Hi, thanks for the contribution :) 
Unfortunately I'm currently in vacation and not at home. Will maybe be able to have a look at it tomorrow. Problem is room.population is undefined when there is no creep. That property should always be present, at least without content. Will add that to the room prototype. 
Thanks again :)

**Comment by cyberblast** [comment]
Should be working now...

**Comment by SirLovi** [comment]
Testing current build ATM.
My second colony is keeping up **only one** Worker.
Spawning of Rangers and Melee is fine though.

**Comment by cyberblast** [comment]
Room.population seems to be static now :/ all rooms contain the same population count/weights like Game. working on a fix...

**Comment by cyberblast** [comment]
I've had the same issue (only one creep in second room). Seems to be working better now. 
Feel free to close after validation

**Comment by SirLovi** [comment]
**Issue fixed**
Closing #27
