### ISSUE TITLE
Privateers needlessly idle

### ISSUE THREAD

**Issue by SirLovi** [cyberblast/screeps.behaviour-action-pattern#49]
Privateers go Idle in the middle of harvesting and can't get back to work
![capture](https://cloud.githubusercontent.com/assets/20193391/17259570/6ea02918-55cc-11e6-8011-0ddcea75ec36.PNG)

**Comment by cyberblast** [comment]
Did you try the latest commit? Had it also somewhen, but not anymore...

**Comment by SirLovi** [comment]
Nothing changed.. They stock up only partially and then their action changes to Null...

![capture1](https://cloud.githubusercontent.com/assets/20193391/17260200/5870017e-55cf-11e6-94a9-943941a7440b.PNG)

**Comment by SirLovi** [comment]
I think this might be caused by empty living pioneers picking up dropped energy from recently dead creeps in the room.. This causes them to have energy but not be completely full so they don't know what to do..
I've killed one pioneer next to this one. It picked up the rest of the energy it needed and then started working normally as intended.

**Comment by cyberblast** [comment]
Ok, think I got it. 
There was a line in harvesting which made it impossible to assign 'not empty' creeps to it. 
Please have a try...

**Comment by SirLovi** [comment]
You da best
