### ISSUE TITLE
Privateers should construct and repair

### ISSUE THREAD

**Issue by SirLovi** [cyberblast/screeps.behaviour-action-pattern#54]
Some sources in remote farm rooms are surrounded by swamps so constructing roads is crucial to be effective.
These roads should also be repaired.

**Comment by cyberblast** [comment]
Yes you are right. Thats what pioneers are currently thought of, but it's not yet working that way. 
And it seems to be a valid point that there is no sense in this restriction and differentiating between pioneer-worker and privateer-worker. This requires a redesign.

**Comment by mikiones** [comment]
mark as to review?

**Comment by cyberblast** [comment]
yup, sry

**Comment by cyberblast** [comment]
but I think we can also just close it..
