### ISSUE TITLE
Claimers should unclaim enemy controllers

### ISSUE THREAD

**Issue by SirLovi** [cyberblast/screeps.behaviour-action-pattern#64]
If controller claimed by different player, unclaim then claim for the player

`room.controller.unclaim();`

**Comment by cyberblast** [comment]
Hi, 
as far as i understand unclaim(), you can only unclaim your own controllers and don't need any creeps for it. 
Controllers claimed by different players can be attacked by creeps with 5 CLAIM parts. 
[attackController](http://support.screeps.com/hc/en-us/articles/203013212-Creep#attackController)
