### ISSUE TITLE
Melee/Ranger/Healer stuck between invading/defending, doing both incorrectly.

### ISSUE THREAD

**Issue by ViezeVingertjes** [cyberblast/screeps.behaviour-action-pattern#85]

**Comment by cyberblast** [comment]
Confirmed. Will have a look at it. 
Thanks!

**Comment by ViezeVingertjes** [comment]
If you replace:

` if( ['guarding','idle'].includes(oldAction)) { `

with

` if( ['guarding','invading','idle'].includes(oldAction)) { `

I think it does the expected, go to the invasion room, than when there, attack on sight.

**Comment by cyberblast** [comment]
no this will alter invading to defending. Invading also handles towers etc. It should work as it is now.  
I will have a second look at it and move that part into "nextAction" soon...

**Comment by cyberblast** [comment]
done. Hope it 's working better now :)
