### ISSUE TITLE
Destroy flag should be effective on owner's spawns

### ISSUE THREAD

**Issue by SirLovi** [cyberblast/screeps.behaviour-action-pattern#87]
In rooms like [THIS](https://screeps.com/a/#!/room/E48S58) which was not intended to be settled, just reserved.
Normally the ''Destroy Flag'' works on any building but creeps refuse to destroy the player's spawn.

**Comment by cyberblast** [comment]
You mean on your own spawn? 
That's not intended. 
Why don't you click "destroy this structure"?

**Comment by SirLovi** [comment]
Forgot to destroy it manually before unclaiming.
You are not allowed to manually destroy buildings in rooms that are not claimed, just reserved.
I want to get rid of that spawn just for the OCD's sake... Having Spawn1,2,3 and then Spawn5 is irritating.

**Comment by cyberblast** [comment]
In creep.action.invading in action.run remove line
        if( !creep.target.my ) 
should be line 103...

**Comment by SirLovi** [comment]
Thank you.
